/**
 * Aggregates disposable email domains from multiple open-source lists,
 * deduplicates, sorts, and writes packages/api/src/data/domains.ts.
 *
 * Run: npx tsx scripts/build-domains.ts
 * Or:  npm run build:domains (from packages/api/)
 */

const SOURCES = [
  {
    name: 'disposable-email-domains (ivolo)',
    url: 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
  },
  {
    name: 'disposable (disposable)',
    url: 'https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.txt',
  },
  {
    name: 'FGRibreau/mailchecker',
    url: 'https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.txt',
  },
];

// Privacy relay services that should NOT be flagged as disposable.
// These are legitimate services that privacy-conscious users rely on.
const ALLOWLIST = new Set([
  // Apple Hide My Email / iCloud Private Relay
  'privaterelay.appleid.com',
  'icloud.com',
  // Firefox Relay
  'relay.firefox.com',
  'mozmail.com',
  // DuckDuckGo Email Protection
  'duck.com',
  // Fastmail masked emails
  'fastmail.com',
  // SimpleLogin (Proton)
  'simplelogin.com',
  'simplelogin.co',
  'aleeas.com',
  // Major providers that sometimes appear on overzealous lists
  'gmail.com',
  'yahoo.com',
  'outlook.com',
  'hotmail.com',
  'protonmail.com',
  'proton.me',
  'icloud.com',
  'me.com',
  'hey.com',
  'pm.me',
  'tutanota.com',
  'tuta.io',
  'zoho.com',
  'aol.com',
  'mail.com',
  'gmx.com',
  'gmx.net',
  'yandex.com',
  'yandex.ru',
]);

function isValidDomain(domain: string): boolean {
  // Must have at least one dot, no spaces, no @, reasonable length
  return (
    domain.length > 0 &&
    domain.length < 256 &&
    domain.includes('.') &&
    !domain.includes(' ') &&
    !domain.includes('@') &&
    !domain.startsWith('.') &&
    !domain.endsWith('.')
  );
}

async function fetchList(source: { name: string; url: string }): Promise<string[]> {
  console.log(`  Fetching: ${source.name}...`);
  const response = await fetch(source.url);

  if (!response.ok) {
    console.warn(`  Warning: Failed to fetch ${source.name} (${response.status}), skipping.`);
    return [];
  }

  const text = await response.text();
  const domains = text
    .split('\n')
    .map((line) => line.trim().toLowerCase())
    .filter((line) => line && !line.startsWith('#') && !line.startsWith('//'));

  console.log(`  Got ${domains.length} domains from ${source.name}`);
  return domains;
}

async function main() {
  console.log('Building disposable domain list...\n');

  // Fetch all sources in parallel
  const results = await Promise.all(SOURCES.map(fetchList));
  const allDomains = results.flat();

  console.log(`\nTotal raw entries: ${allDomains.length}`);

  // Deduplicate, validate, and filter allowlist
  const domainSet = new Set<string>();
  let invalidCount = 0;
  let allowlistedCount = 0;

  for (const domain of allDomains) {
    if (!isValidDomain(domain)) {
      invalidCount++;
      continue;
    }
    if (ALLOWLIST.has(domain)) {
      allowlistedCount++;
      continue;
    }
    domainSet.add(domain);
  }

  const sorted = [...domainSet].sort();

  console.log(`Invalid entries skipped: ${invalidCount}`);
  console.log(`Allowlisted entries skipped: ${allowlistedCount}`);
  console.log(`Final unique domains: ${sorted.length}\n`);

  // Generate TypeScript source
  const lines = sorted.map((d) => `  '${d}',`);
  const source = `// Auto-generated by scripts/build-domains.ts — DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}
// Sources: ${SOURCES.map((s) => s.name).join(', ')}
// Total domains: ${sorted.length}

const DOMAINS_LIST: readonly string[] = [
${lines.join('\n')}
];

export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set(DOMAINS_LIST);
`;

  const fs = await import('node:fs');
  const path = await import('node:path');
  const { fileURLToPath } = await import('node:url');
  const filePath = fileURLToPath(new URL('../src/data/domains.ts', import.meta.url));
  fs.writeFileSync(filePath, source, 'utf-8');

  console.log(`Written to src/data/domains.ts (${sorted.length} domains)`);

  // Also output JSON for the web package (used by domain lookup pages + sitemap)
  const webJsonPath = path.resolve(
    fileURLToPath(new URL('../..', import.meta.url)),
    'web/src/data/domains.json',
  );
  fs.writeFileSync(webJsonPath, JSON.stringify(sorted), 'utf-8');
  console.log(`Written to packages/web/src/data/domains.json (${sorted.length} domains)`);

  // Quick stats
  const tlds = new Map<string, number>();
  for (const d of sorted) {
    const tld = '.' + d.split('.').pop()!;
    tlds.set(tld, (tlds.get(tld) ?? 0) + 1);
  }
  const topTlds = [...tlds.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
  console.log('\nTop TLDs:');
  for (const [tld, count] of topTlds) {
    console.log(`  ${tld}: ${count}`);
  }
}

main().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
